name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
        registry-url: 'https://registry.npmjs.org'

    - run: npm install

    - name: Install Protoc
      uses: paperback-ios/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
